import type { Metadata } from 'next';
import { SiteFooter, SiteHeader } from '@/components/site-header';

export const metadata: Metadata = {
  title: 'Improve the Record',
  description: 'Share an observation, suggest a source, or flag a problem in the Virality Research record.',
  openGraph: { title: 'Improve the Record', description: 'Share an observation, suggest a source, or flag a problem in the Virality Research record.' },
};

export default function ContributePage() { return <><SiteHeader /><main className="frame contribution-page"><p className="kicker">Improve the record</p><h1 className="page-title">Make the work better.</h1><p className="page-intro">Bring something that sharpens the question, improves a source, or corrects the public record. Personal observations and research evidence are useful in different ways, so they stay separate.</p><div className="contribution-paths"><section id="observation"><span>01</span><div><p className="tag">An observation</p><h2>Share something you have seen spread.</h2><p>A story, phrase, game, behaviour, product, or post that moved through a community. It can help generate a question; it does not become evidence on its own.</p><a className="text-link" href="mailto:vineetagarwal98@gmail.com?subject=Virality%20Research%20observation">Share an observation <span aria-hidden="true">→</span></a></div></section><section id="research"><span>02</span><div><p className="tag">The research record</p><h2>Suggest a source or flag a problem.</h2><p>Offer a primary source, contrary evidence, a missing limitation, a bad link, or a correction. The aim is a more accurate record, not a smoother story.</p><a className="text-link" href="mailto:vineetagarwal98@gmail.com?subject=Virality%20Research%20correction%20or%20source">Improve the record <span aria-hidden="true">→</span></a></div></section></div><section className="page-section contribution-notes"><div className="section-label">What happens next</div><div className="prose"><p>Submissions are reviewed, not automatically published. A submission does not imply endorsement, and no response time is guaranteed. Please do not send copyrighted material unless you have the right to share it.</p></div></section></main><SiteFooter /></>; }
