import Link from 'next/link';

const questions = [
  'Why do people voluntarily pass some information along?',
  'How does an idea move between social groups?',
  'Is adopting a product different from sharing a story?',
  'Where do people end and algorithms begin?',
];

export default function Home() {
  return (
    <main>
      <div className="status-strip"><div className="frame status-strip__inner"><span className="status-dot" /><p><strong>Essential-03 underway</strong><span aria-hidden="true"> · </span>Updated 1 September 2026</p><Link href="/research">See the current inquiry <span aria-hidden="true">→</span></Link></div></div>
      <header className="site-header frame"><Link className="wordmark" href="/">Virality <span>Research</span></Link><nav aria-label="Primary navigation"><Link href="/research">Research</Link><Link href="/method">Method</Link><Link href="/sources">Sources</Link><Link href="/contribute">Contribute</Link></nav></header>
      <section className="hero frame"><div className="hero__eyebrow">A public learning project</div><div className="hero__grid"><div><h1>Why do some things spread?</h1></div><div className="hero__copy"><p className="lead">I’m reading research on why information, ideas, behaviours, culture, and products travel farther and faster than others.</p><p>Not to offer a finished formula. To make the question clearer, source by source, in public.</p><div className="actions"><Link className="button button--ink" href="/research">Follow the research <span aria-hidden="true">→</span></Link><Link className="text-link" href="/sources">Browse the reading list <span aria-hidden="true">→</span></Link></div></div></div><div className="ledger-line"><span>Research record / 01</span><span>140 catalogued sources</span><span>132 reviewed evidence cards</span></div></section>
      <section className="origin frame section-rule"><div className="section-label">Origin</div><div className="origin__content"><h2>A familiar mystery, examined carefully.</h2><p>I build products and write online. Like most people who make things, I hope the work will occasionally reach the people it is for. Usually it doesn’t travel very far.</p><p>Once, a LinkedIn post reached roughly 200,000 views. I still couldn’t say exactly why. Then I started noticing how songs, games, phrases, and stories had travelled between childhoods and communities long before digital feeds existed.</p><p>That uncertainty is the starting point here: read the literature, separate what has been shown from what is only plausible, and make the learning inspectable.</p></div></section>
      <section className="distinctions frame section-rule"><div className="section-label">One useful distinction</div><div><h2>Spread is not one thing.</h2><div className="distinction-grid"><article><span>01</span><h3>Sharing ≠ adoption</h3><p>A story can be passed on without changing what anyone does.</p></article><article><span>02</span><h3>People ≠ algorithms</h3><p>Interpersonal transmission and feed distribution create different opportunities to spread.</p></article><article><span>03</span><h3>Acquisition ≠ retention</h3><p>A burst of attention does not establish lasting product value.</p></article></div></div></section>
      <section className="questions frame section-rule"><div className="section-label">Questions being explored</div><div className="questions__body"><h2>No shortcuts. Better questions first.</h2><ol>{questions.map((question, index) => <li key={question}><span>0{index + 1}</span>{question}</li>)}</ol><Link className="text-link" href="/research">Explore the current questions <span aria-hidden="true">→</span></Link></div></section>
      <section className="current frame section-rule"><div className="section-label">Now investigating</div><div className="current__card"><div><span className="tag tag--amber">Current checkpoint</span><h2>Essential-03</h2><p className="current__topic">Economic diffusion, referrals, seeding, and platform network effects.</p></div><div className="current__answer"><p>The next reading batch asks when growth is created by individual invitations, when it depends on network structure, and what evidence would let us tell the difference.</p><Link className="text-link" href="/research">Read what is being examined <span aria-hidden="true">→</span></Link></div></div></section>
      <section className="method-preview frame section-rule"><div className="section-label">The public record</div><div className="method-preview__body"><h2>How a claim earns its place.</h2><div className="lifecycle" aria-label="Research lifecycle"><span>Source</span><i aria-hidden="true">→</i><span>Extracted record</span><i aria-hidden="true">→</i><span>Verified evidence</span><i aria-hidden="true">→</i><span>Thematic synthesis</span><i aria-hidden="true">→</i><span>Public guidance</span></div><p>Evidence reviewed means source-level verification. It does not mean a cross-source conclusion has been published.</p><Link className="text-link" href="/method">Read the research contract <span aria-hidden="true">→</span></Link></div></section>
      <section className="participation frame section-rule"><div className="section-label">Take part</div><div className="participation__body"><h2>Help make the inquiry better.</h2><div className="participation__cards"><article><h3>Share an observation or question</h3><p>Tell me about something you have seen travel through a community, childhood, product, or feed.</p><Link href="/contribute">Share thoughtfully <span aria-hidden="true">→</span></Link></article><article><h3>Improve the research</h3><p>Suggest a primary source, offer contrary evidence, or flag an error in the public record.</p><Link href="/contribute">Contribute to the record <span aria-hidden="true">→</span></Link></article></div></div></section>
      <footer className="site-footer frame"><p>Virality Research · A living public learning project by Vineet.</p><div><Link href="/corrections">Corrections</Link><Link href="/privacy">Privacy</Link></div></footer>
    </main>
  );
}
