'use client';

import { useMemo, useState } from 'react';
import { ExternalLink, Copy, Check } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { NativeSelect } from '@/components/ui/native-select';

export type SourceRecord = { id: string; title: string; authors: string; year: number; venue: string; sourceType: string; topic: string; whyItMatters: string; url: string; doi: string | null; state: string; accessNote: string; lastReviewed: string | null; };

export function SourceLibrary({ sources }: { sources: SourceRecord[] }) {
  const [query, setQuery] = useState(''); const [topic, setTopic] = useState('All topics'); const [type, setType] = useState('All types'); const [state, setState] = useState('All states'); const [period, setPeriod] = useState('Any period'); const [copied, setCopied] = useState<string | null>(null);
  const topics = useMemo(() => [...new Set(sources.map((source) => source.topic))].sort(), [sources]);
  const types = useMemo(() => [...new Set(sources.map((source) => source.sourceType))].sort(), [sources]);
  const filtered = useMemo(() => sources.filter((source) => { const value = `${source.title} ${source.authors} ${source.topic} ${source.doi ?? ''} ${source.id}`.toLowerCase(); const matchesPeriod = period === 'Any period' || (period === '2020–2026' && source.year >= 2020) || (period === '2000–2019' && source.year >= 2000 && source.year < 2020) || (period === 'Before 2000' && source.year < 2000); return value.includes(query.toLowerCase()) && (topic === 'All topics' || source.topic === topic) && (type === 'All types' || source.sourceType === type) && (state === 'All states' || source.state === state) && matchesPeriod; }), [sources, query, topic, type, state, period]);
  async function copy(value: string, id: string) { await navigator.clipboard.writeText(value); setCopied(id); window.setTimeout(() => setCopied(null), 1800); }
  return <div className="source-library"><div className="source-controls"><label className="search-label"><span>Search the catalogue</span><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Title, author, topic, DOI…" /></label><div className="filter-grid"><NativeSelect aria-label="Filter by topic" value={topic} onChange={(event) => setTopic(event.target.value)}><option>All topics</option>{topics.map((item) => <option key={item}>{item}</option>)}</NativeSelect><NativeSelect aria-label="Filter by source type" value={type} onChange={(event) => setType(event.target.value)}><option>All types</option>{types.map((item) => <option key={item}>{item}</option>)}</NativeSelect><NativeSelect aria-label="Filter by research state" value={state} onChange={(event) => setState(event.target.value)}><option>All states</option>{['Catalogued', 'Evidence reviewed', 'Metadata only', 'Deferred'].map((item) => <option key={item}>{item}</option>)}</NativeSelect><NativeSelect aria-label="Filter by publication period" value={period} onChange={(event) => setPeriod(event.target.value)}><option>Any period</option><option>2020–2026</option><option>2000–2019</option><option>Before 2000</option></NativeSelect></div></div><p className="result-count">{filtered.length} {filtered.length === 1 ? 'source' : 'sources'} shown</p><div className="source-results">{filtered.map((source) => <article className="source-card" key={source.id}><div className="source-card__meta"><span>{source.id}</span><span className={`state state--${source.state.toLowerCase().replaceAll(' ', '-')}`}>{source.state}</span></div><h2>{source.title}</h2><p className="source-card__authors">{source.authors} · {source.year}</p><p className="source-card__venue">{source.venue} · {source.sourceType} · {source.topic}</p><p className="source-card__why">{source.whyItMatters}</p><div className="source-card__foot"><span>{source.accessNote}</span><div>{source.doi && <button className="copy-button" onClick={() => copy(source.doi!, source.id)} aria-label={`Copy DOI for ${source.title}`}>{copied === source.id ? <Check size={14} /> : <Copy size={14} />} {copied === source.id ? 'Copied' : 'DOI'}</button>}<a href={source.url} target="_blank" rel="noreferrer">Open source <ExternalLink size={14} /></a></div></div></article>)}</div>{filtered.length === 0 && <div className="empty-state"><h2>Nothing matches those filters.</h2><p>Try clearing a filter or searching by author, title, topic, or DOI.</p></div>}</div>;
}
