import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { SiteFooter, SiteHeader } from '@/components/site-header';

const entries: Record<string, { number: string; title: string; deck: string; date: string; body: string[] }> = {
  'why-this-project-exists': { number: '01', title: 'Why this project exists', deck: 'An unexplained post opened a much older question.', date: '1 September 2026', body: ['I build products and write online. Like most people who make things, I want the work to find the people it could matter to. Usually, it reaches a modest number of people and then disappears from view.', 'One LinkedIn post reached roughly 200,000 views. I was grateful, but I could not explain it with confidence. A neat story would have been satisfying; it would not have been knowledge.', 'The deeper question is older than social feeds. Songs, playground games, sayings, and stories have travelled between people and places for generations. This project begins from that larger puzzle and reads outward from it: transmission, adoption, networks, incentives, attention, culture, and product value.', 'The public record is an attempt to make the learning visible before it turns into advice.'] },
  'evidence-cards': { number: '02', title: 'What an evidence card is—and is not', deck: 'A compact way to retain source-level context without pretending it is a conclusion.', date: '1 September 2026', body: ['An evidence card is a structured note tied to one original source and one precise locator. It records what was studied, what the source supports, the evidence type, the result, and the limitation that keeps the claim in bounds.', 'It is not a quote collection. It is not a scorecard for making a source agree with a preselected idea. And it is not a cross-source synthesis.', 'That distinction is useful because a vivid result can look more general than it is. A source may concern stated sharing rather than observed sharing; a product recommendation rather than sustained adoption; a particular platform interface rather than a durable human mechanism.', 'The cards keep those details available until there is enough verified evidence to compare sources responsibly.'] },
  'a-repair-is-part-of-the-method': { number: '03', title: 'A repair is part of the method', deck: 'An extraction artifact was not a research finding. It was still important to record.', date: '1 September 2026', body: ['One source contained a repeated vector-plot sequence in its machine-readable text layer. Left untreated, that artifact would make the extracted record noisier and less useful for review.', 'The response was intentionally narrow: adjust the normalizer only for long runs of repeated plot markers, regenerate the affected batch, and re-run the extraction, coverage, locator, duplication, and adversarial checks.', 'This does not say anything about virality. It does say something about the conditions under which a research record should be trusted: corrections need a boundary, an audit trail, and a chance to fail again.', 'A public learning project should not hide this kind of repair. The work is stronger when the repair is visible.'] },
};

export function generateStaticParams() { return Object.keys(entries).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const entry = entries[slug]; if (!entry) return {}; return { title: entry.title, description: entry.deck, openGraph: { title: entry.title, description: entry.deck } }; }
export default async function JournalEntry({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const entry = entries[slug]; if (!entry) notFound(); return <><SiteHeader /><main className="frame journal-entry"><p className="kicker">Journal / {entry.number} · {entry.date}</p><h1 className="page-title">{entry.title}</h1><p className="page-intro">{entry.deck}</p><article className="journal-body">{entry.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</article><Link className="text-link" href="/research">Return to the research record →</Link></main><SiteFooter /></>; }
